GENERAL:
  SEED: 0
  CHECK_GEN: 1
  NAME: test
  PROBLEM_TYPE: p2
  USE_TIMESTR: false

GA:
  POP_SIZE: 25
  NUM_GEN: 200

INV_SPEC:
  NUM_WARMUP: 0
  QUERY_SELECTOR_TYPE: ig  # ig or rand
  INTERACT_PERIOD: 25
  MAX_QUERIES_PER: 3
  MAX_QUERIES: 20
  INFER_TYPE: gp
  POP_EXTRACT_TYPE: F
  BETA: 10.
  INPUT_NORMALIZE: true

GP:
  HORIZONTAL_LENGTH: 0.3  # ell in RBF kernel
  VERTICAL_VARIATION: 1.0  # sigma_f in RBF kernel
  NOISE_LEVEL: 0.1  # sigma_n in RBF kernel
  NOISE_PROBIT: 0.5  # sigma in Probit model

HUMAN:
  BETA: 10
  TYPE: range_hard
  PERFECT_RANK: true
  INDIFFERENCE: 0.01
