GENERAL:
  SEED: 0
  CHECK_GEN: 1
  NAME: test
  PROBLEM_TYPE: p2
  USE_TIMESTR: false

GA:
  POP_SIZE: 25
  NUM_GEN: 200

INV_SPEC:
  NUM_WARMUP: 0
  QUERY_SELECTOR_TYPE: rand
  INTERACT_PERIOD: 25
  MAX_QUERIES_PER: 3
  MAX_QUERIES: 20
  INFER_TYPE: nn
  POP_EXTRACT_TYPE: F
  BETA: 10.
  INPUT_NORMALIZE: true

NN:
  MAX_UPDATES: 500
  LEARNING_RATE: 0.001
  LR_PERIOD: 1000
  BATCH_SIZE: 16
  TRADEOFF: 0.01
  ARCHITECTURE:
    - 20
    - 20
  ACTIVATION: ReLU

HUMAN:
  BETA: 10
  TYPE: range_hard  # speed or range or range_hard (range with hard constraints)
  PERFECT_RANK: true
  INDIFFERENCE: 0.01
