GENERAL:
  SEED: 0
  CHECK_GEN: 1
  NUM_WORKERS: 9 
  NAME: init
  INIT_OBJ_PATH: null
  # INIT_OBJ_PATH: /Users/kaichieh/Desktop/SDCPS/src/scratch/swri/NSGA2/default/objective_20


GA:
  POP_SIZE: 25
  NUM_GEN: 20
  # NUM_GEN: 11
