GENERAL:
  SEED: 0
  CHECK_GEN: 5
  NAME: rand_1

GA:
  POP_SIZE: 50
  NUM_GEN: 100

INV_SPEC:
  NUM_WARMUP: 20
  QUERY_SELECTOR_TYPE: rand
  INTERACT_PERIOD: 10
  MAX_QUERIES_PER: 10
  MAX_QUERIES: 100
  INFER_TYPE: nn
  POP_EXTRACT_TYPE: F
  BETA: 10.
  INPUT_NORMALIZE: true

NN:
  MAX_UPDATES: 500
  LEARNING_RATE: 0.001
  LR_PERIOD: 1000
  BATCH_SIZE: 4
  TRADEOFF: 0.01
  ARCHITECTURE:
    - 20
    - 20
  ACTIVATION: ReLU

HUMAN:
  BETA: 10
  TYPE: plain
  PERFECT_RANK: false
  INDIFFERENCE: 0.01
