GENERAL:
  SEED: 4
  CHECK_GEN: 1
  NUM_WORKERS: 9
  NAME: test_buffer_200_5
  # AGENT_PATH: scratch/swri/modular/agent/agent
  AGENT_PATH: scratch/swri/modular/buffer/agent

GA:
  POP_SIZE: 25
  NUM_GEN: 30
