GENERAL:
  NAME: input_un
  SEED: 0
  CHECK_GEN: 5

GA:
  POP_SIZE: 25
  NUM_GEN: 50

INV_SPEC:
  NUM_WARMUP: 20
  BETA: 10.0
  MAX_QUERY: 50
  NUM_QUERY_PER: 5
  POP_EXTRACT_TYPE: F
  QUERY_SELECTOR_TYPE: ig
  INTERACT_PERIOD: 10
  INPUT_NORMALIZE: false

GP:
  HORIZONTAL_LENGTH: 0.3
  VERTICAL_VARIATION: 1.0
  NOISE_LEVEL: 0.1
  NOISE_PROBIT: 0.5

HUMAN:
  BETA: 10.0
  TYPE: plain

